version: '3.3'
services:
  php-apache:
    container_name: php-apache
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80
  db:
    container_name: db
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: base
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "9906:3306"